Clean up debugger code
GillianPlatform/Gillian pull request #189
Opened 2022-11-28 18:45 UTC by NatKarmios

Resolves #139

2022-11-30 17:03 UTC, giltho requested changes

2022-11-30 17:03 UTC, giltho commented on scripts/watch_odoc.sh
> +  echo "Watching with fswatch"
woopsie

2022-11-30 17:05 UTC, NatKarmios commented on scripts/watch_odoc.sh
> +  echo "Watching with fswatch"
wops
fed444d75b0519c548ea6f1961a1949466c991e5

2022-12-01 13:01 UTC, giltho commented on GillianCore/debugging/utils/exec_map.ml
>  module L = Logging
How about some module-level documentation about what an exec map is, like what it's for, what it looks like.
The annotations on the type lack context

2022-12-01 13:01 UTC, giltho commented on GillianCore/debugging/utils/unify_map.ml
>  module DL = Debugger_log
Same as exec_map, you can even reference exec_map

2022-12-01 13:02 UTC, giltho commented
But at the same time having sphinx makes it a LOT more readable so 🤷

2022-12-05 15:41 UTC, giltho approved these changes

2022-12-05 15:41 UTC, merged