205 rid of AFail/ASucc
GillianPlatform/Gillian pull request #206
Opened 2023-01-15 14:45 UTC by prnvbn

2023-01-15 14:58 UTC, giltho requested changes
Thank you! Just a tiny change :)

2023-01-15 15:01 UTC, prnvbn commented on Gillian-C/lib/MonadicSMemory.ml
> +let lift_res res = res
of course 🤦

2023-01-30 23:11 UTC, giltho commented
Oh god completely forgot to merge this

2023-01-30 23:11 UTC, merged

2023-01-31 16:21 UTC, NatKarmios commented
Resolves #205

2023-01-31 16:24 UTC, NatKarmios commented
@prnvbn, pro tip, if you put "Resolves #xx" in your PR description, it'll automatically close the relevant issue when it's merged :)

See #156 for an example.